spring:
  application:
    name: HelloServer

server:
  port: 7789

eureka:
#  password: password
  client:
    serviceUrl:
#      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}